In [5]:
total = 0
count = 0
numbers = input("Enter a number :  (<Enter Key> to quit)")
while numbers != "":
    try:
        x = float(numbers)
        count += 1
        total = total + x
    except ValueError:
        print('NOT a number! Ignored..')
    numbers = input("Enter a number :  (<Enter Key> to quit)")
avg = total / count
print("\n average is", avg)

Enter a number :  (<Enter Key> to quit)15
Enter a number :  (<Enter Key> to quit)15
Enter a number :  (<Enter Key> to quit)15
Enter a number :  (<Enter Key> to quit)

 average is 15.0


In [6]:
# 2개 이상의 숫자를 입력받아 리스트에 저장하는 함수
def numbers():
    X=[]    # X에 빈 리스트를 할당합니다.
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)    # float형으로 변환한 숫자 입력을 리스트에 추가합니다.
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:  # 저장된 숫자가 2개 이상일 때만 리턴합니다.
            return X

X=numbers()

print('X :', X)

Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)
X : [1.0, 2.0, 3.0, 4.0, 5.0]


In [3]:
import array as arr

mylist = [1, 2, 3]   # 이것은 파이썬 built-in list입니다. 
print(type(mylist))

mylist.append('4')  # mylist의 끝에 character '4'를 추가합니다. 
print(mylist)

mylist.insert(1, 5)  # mylist의 두번째 자리에 5를 끼워넣습니다.
print(mylist)

myarray = arr.array('i', [1, 2, 3])   # 이것은 array입니다. import array를 해야 쓸 수 있습니다.
print(type(myarray))

# 아래 라인의 주석을 풀고 실행하면 에러가 납니다.
#myarray.append('4')    # myarray의 끝에 character '4'를 추가합니다. 
print(myarray)

myarray.insert(1, 5)    # myarray의 두번째 자리에 5를 끼워넣습니다.
print(myarray)

<class 'list'>
[1, 2, 3, '4']
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


In [7]:
total = 0.0
for i in range(len(X)):
    total = total + X[i]
mean = total / len(X)

print('sum of X: ', total)

sum of X:  15.0


In [8]:
def median(nums):  		# nums : 리스트를 지정하는 매개변수
    nums.sort()					# sort()로 리스트를 순서대로 정렬
    size = len(nums)
    p = size // 2
    if size % 2 == 0:		   # 리스트의 개수가 짝수일때 
        pr = p   
        pl = p-1
        mid= float((nums[pl]+nums[pr])/2)    
    else:								# 리스트의 개수가 홀수일때
        mid = nums[p]
    return mid

print('X :', X)
median(X)						# 매개변수의 값으로 X를 사용함

X : [1.0, 2.0, 3.0, 4.0, 5.0]


3.0

In [9]:
def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

means(X)

3.0

In [10]:
avg = means(X)

def std_dev(nums, avg):
   texp = 0.0
   for i in range(len(nums)):
       texp = texp + (nums[i] - avg)**2 
   return (texp/(len(nums)-1)) ** 0.5  

std_dev(X,avg)

1.5811388300841898

In [11]:
med = median(X)
avg = means(X)
std = std_dev(X, avg)
print("당신이 입력한 숫자{}의 ".format(X))
print("중앙값은{}, 평균은{}, 표준편차는{}입니다.".format(med, avg, std))

당신이 입력한 숫자[1.0, 2.0, 3.0, 4.0, 5.0]의 
중앙값은3.0, 평균은3.0, 표준편차는1.5811388300841898입니다.


In [12]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print(B)
print(type(B))
print()
print(C)
print(type(C))
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>

['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [13]:
A = np.arange(10).reshape(2,5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print(A.shape)
print(A.ndim)
print(A.size)

(2, 5)
2
10


In [14]:
A = np.arange(10)
print('A: ', A)
B = np.arange(10).reshape(2,5)
print('B: ', B)
C = np.arange(10).reshape(3,3)  # 이 줄에서 에러가 날 것입니다.
print('C: ', C)

A:  [0 1 2 3 4 5 6 7 8 9]
B:  [[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,3)

In [17]:
A= np.arange(6).reshape(2,3)
print(A)
print(A.dtype)
print(type(A))
print()

B = np.array([0,1,2,3,4,5])  
print(B)
print(B.dtype)
print(type(B))
print()

C = np.array([0,1,2,3,'4',5])
print(C)
print(C.dtype)
print(type(C))
print()

D = np.array([0,1,2,3,[4,5],6])  # 이런 ndarray도 만들어질까요?
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>

[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>

['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>

[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>
